export default [
  {
    key: 'id',
    caption: 'Id',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'idAlias',
    caption: 'Id Alias',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'amount',
    caption: 'Amount',
    fieldType: 'textAmount',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'status',
    caption: 'Status',
    fieldType: 'text',
    rules: '',
    type: '',
    value: '',
  },
  {
    key: 'agentName',
    caption: 'Agent Name',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'outletName',
    caption: 'Outlet Name',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'merchantName',
    caption: 'Merchant Name',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'acquirerTypeName',
    caption: 'Acquirer Type Name',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'shareAcquirer',
    caption: 'Share Acquirer',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'sharePartner',
    caption: 'Share Partner',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'shareMerchant',
    caption: 'Share Merchant',
    fieldType: 'text',
    rules: '',
    value: '',
  },
  {
    key: 'shareMerchantWithPartner',
    caption: 'Share Merchant with Partner',
    fieldType: 'text',
    rules: '',
    value: '',
  },
  {
    key: 'settlementStattus',
    caption: 'Settlement Status',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'referenceNumber',
    caption: 'Reference Number',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'updatedAt',
    caption: 'Date',
    fieldType: 'date',
    type: 'text',
    value: '',
  },
]
