import Chance from 'chance'
const faker = new Chance()

export default [
  {
    key: 'name',
    caption: 'Name',
    fieldType: 'text',
    rules: 'required|max:50',
    type: 'text',
    value: '',
  },

  {
    key: 'companyForm',
    caption: 'Company Form',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'email',
    caption: 'Email',
    fieldType: 'text',
    rules: 'required|email',
    type: 'text',
    value: '',
  },
  {
    key: 'website',
    caption: 'Website',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'phoneNumber',
    caption: 'Phone Number',
    fieldType: 'text',
    rules: 'max:30',
    type: 'text',
    value: '',
  },
  {
    key: 'taxCardNumber',
    caption: 'Tax Card Number',
    fieldType: 'text',
    rules: 'numeric',
    type: 'number',
    value: '',
  },
  {
    key: 'bankName',
    caption: 'Bank Name',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'bankBranchName',
    caption: 'Bank Branch Name',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'bankAccountName',
    caption: 'Bank Account Name',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'bankAccountNumber',
    caption: 'Bank Account Number',
    fieldType: 'text',
    rules: 'numeric',
    type: 'number',
    value: '',
  },
  // {
  //   key: "scannedBankStatementresourceId",
  //   caption: "Scanned Bank Statement Resource Id",
  //   fieldType: "text",
  //   rules: "",
  //   type: "file",
  //   value: ""
  // },
  // {
  //   key: "scannedSkmenkumhamResourceId",
  //   caption: "Scanned Skmenkunham Resource Id",
  //   fieldType: "text",
  //   rules: "",
  //   type: "file",
  //   value: ""
  // },
  // {
  //   key: "scannedSiupResourceId",
  //   caption: "Scanndes Siup Resource Id",
  //   fieldType: "text",
  //   rules: "",
  //   type: "file",
  //   value: ""
  // },
  // {
  //   key: "scannedSkdpResourceId",
  //   caption: "Scanndes Skdp Resource Id",
  //   fieldType: "text",
  //   rules: "",
  //   type: "file",
  //   value: ""
  // },
  {
    key: 'ownerName',
    caption: 'Owner Name',
    fieldType: 'text',
    rules: 'required',
    type: 'text',
    value: '',
  },
  {
    key: 'ownerOccupation',
    caption: 'Owner Occupation',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'ownerEmail',
    caption: 'Owner Email',
    fieldType: 'text',
    rules: 'required|email',
    type: 'text',
    value: '',
  },
  {
    key: 'ownerPhoneNumber',
    caption: 'Owner Phone Number',
    fieldType: 'text',
    rules: 'max:30',
    type: 'text',
    value: '',
  },
  {
    key: 'ownerIdCardNumber',
    caption: 'Owner Id Card Number',
    fieldType: 'text',
    rules: 'numeric',
    type: 'number',
    value: '',
  },
  {
    key: 'ownerIdCardType',
    caption: 'Owner Id Card Type',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'ownerTaxCardNumber',
    caption: 'Owner Tax Card Number',
    fieldType: 'text',
    rules: 'numeric',
    type: 'number',
    value: '',
  },
  {
    key: 'description',
    caption: 'Description',
    fieldType: 'textarea',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'createdAt',
    caption: 'Date',
    fieldType: 'date',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'archivedAt',
    caption: 'Archived At',
    fieldType: 'date',
    rules: '',
    type: 'text',
    value: '',
  },
]

export const fakeData = {
  idAlias: faker.bb_pin(),
  name: faker.word(),
  shortName: faker.word(),
  description: faker.word(),
  companyForm: faker.word(),
  email: faker.email(),
  website: faker.url(),
  phoneNumber: faker.phone(),
  taxCardNumber: faker.integer({ min: 0 }),
  bankName: faker.company(),
  bankBranchName: faker.word(),
  bankAccountName: faker.word(),
  bankAccountNumber: faker.integer({ min: 0 }).toString(),
  ownerName: faker.name(),
  ownerOccupation: faker.word(),
  ownerEmail: faker.email(),
  ownerPhoneNumber: faker.phone(),
  ownerIdCardNumber: faker.integer({ min: 0 }).toString(),
  ownerIdCardType: faker.word(),
  ownerTaxcardNumber: faker.integer({ min: 0 }).toString(),
}
