export default [
  {
    key: 'acquirerConfigId',
    caption: 'Acquirer Config Name',
    fieldType: 'select',
    rules: 'required',
    type: 'select',
    value: '',
  },
  {
    key: 'agentId',
    caption: 'Agent Name',
    rules: 'required',
    type: 'select',
    fieldType: 'select',
    value: '',
  },
  {
    key: 'acquirerTerminalId',
    caption: 'Acquirer TID',
    rules: 'required',
    type: 'select',
    fieldType: 'select',
    value: '',
  },
  {
    key: 'latestSettleBatchId',
    caption: 'Latest Settle Batch',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'batchNumberCounter',
    caption: 'Batch Number Counter',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'config',
    caption: 'Config',
    fieldType: 'config',
    rules: 'required',
    type: 'text',
    value: '',
  },
  {
    key: 'description',
    caption: 'Description',
    fieldType: 'textarea',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'createdAt',
    caption: 'Created At',
    fieldType: 'date',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'archivedAt',
    caption: 'Archived At',
    fieldType: 'date',
    rules: '',
    type: 'text',
    value: '',
  },
]
