export default [
  {
    key: 'name',
    caption: 'Name',
    fieldType: 'text',
    rules: 'required|max:50',
    type: 'text',
    value: '',
  },
  {
    key: 'email',
    caption: 'Email',
    fieldType: 'text',
    rules: 'required|email|max:50',
    type: 'text',
    value: '',
  },
  {
    key: 'username',
    caption: 'Username',
    fieldType: 'text',
    rules: 'required|max:50',
    type: 'text',
    value: '',
  },
  {
    key: 'idCardNumber',
    caption: 'Id Card Number',
    fieldType: 'text',
    rules: 'numeric',
    type: 'number',
    value: '',
  },
  {
    key: 'idCardType',
    caption: 'Id Card Type',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'occupation',
    caption: 'Occupation',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'phoneNumber',
    caption: 'Phone Number',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'streetAddress',
    caption: 'Street Address',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'locacity',
    caption: 'Locacity',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'district',
    caption: 'District',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'city',
    caption: 'City',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'province',
    caption: 'Province',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'postalCode',
    caption: 'Postal Code',
    fieldType: 'text',
    rules: 'numeric',
    type: 'text',
    value: '',
  },
  {
    key: 'description',
    caption: 'Description',
    fieldType: 'textarea',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'merchantId',
    caption: 'Merchant Id',
    fieldType: 'hidden',
    rules: '',
    type: 'hidden',
    value: '',
  },
]

// userId: "",
// merchantId: "",
