export default [
  {
    key: 'name',
    caption: 'Name',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'acquirerCompanyId',
    caption: 'Acquirer Company ID',
    fieldType: 'hidden',
    rules: 'required',
    type: 'text',
    value: '',
  },
  {
    key: 'acquirerCompanyName',
    caption: 'Acquirer Company Name',
    fieldType: 'select',
    rules: 'required',
    type: 'text',
    value: '',
  },
  {
    key: 'config',
    caption: 'Config',
    fieldType: 'textarea',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'description',
    caption: 'Description',
    fieldType: 'textarea',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'createdAt',
    caption: 'Created At',
    fieldType: 'date',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'archivedAt',
    caption: 'Archived At',
    fieldType: 'date',
    rules: '',
    type: 'text',
    value: '',
  },
]
