export default [
  {
    key: 'name',
    caption: 'Name',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'mid',
    caption: 'MID',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'tid',
    caption: 'TID',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'acquirerTerminalCommonId',
    caption: 'Acquirer Terminal Common',
    fieldType: 'select',
    rules: 'required',
    type: 'text',
    value: '',
  },
  {
    key: 'traceNumberCounter',
    caption: 'Trace Number Counter',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'type',
    caption: 'Type',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'config',
    caption: 'Config',
    fieldType: 'textarea',
    rules: '',
    type: 'text',
    value: '{}',
  },
  {
    key: 'description',
    caption: 'Description',
    fieldType: 'textarea',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'createdAt',
    caption: 'Created At',
    fieldType: 'date',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'archivedAt',
    caption: 'Archived At',
    fieldType: 'date',
    rules: '',
    type: 'text',
    value: '',
  },
]
