export default [
  {
    key: 'name',
    caption: 'Name',
    fieldType: 'text',
    rules: 'required|max:50',
    type: 'text',
    value: '',
  },
  {
    key: 'handler',
    caption: 'Handler',
    fieldType: 'select',
    rules: 'required',
    type: 'select',
    value: '',
  },
  {
    key: 'config',
    caption: 'Config',
    fieldType: 'config',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'sandbox',
    caption: 'Sandbox',
    fieldType: 'select',
    rules: 'required',
    type: 'text',
    value: '',
  },
  {
    key: 'merchantId',
    caption: 'Merchant Name',
    fieldType: 'select',
    rules: '',
    type: 'select',
    value: '',
    props: 'merchants',
  },
  {
    key: 'description',
    caption: 'Description',
    fieldType: 'textarea',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'createdAt',
    caption: 'Date',
    fieldType: 'date',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'archivedAt',
    caption: 'Archived At',
    fieldType: 'date',
    rules: '',
    type: 'text',
    value: '',
  },
]
