export default [
  {
    key: 'name',
    caption: 'Name',
    fieldType: 'text',
    rules: 'required|max:50',
    type: 'text',
    value: '',
  },
  {
    key: 'config',
    caption: 'Config',
    fieldType: 'textarea',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'handler',
    caption: 'Handler',
    fieldType: 'text',
    rules: 'required|max:50',
    type: 'text',
    value: '',
  },
  {
    key: 'sandbox',
    caption: 'Sandbox',
    fieldType: 'select',
    rules: 'required',
    type: 'text',
    value: '',
  },
  {
    key: 'acquirerConfigKvs',
    caption: 'Acquirer Key Values',
    fieldType: 'textarea',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'description',
    caption: 'Description',
    fieldType: 'textarea',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'merchantName',
    caption: 'Merchant Name',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
]
