export default [
  {
    key: 'name',
    caption: 'Name',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'pattern',
    caption: 'Pattern',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'priority',
    caption: 'Priority',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'validation',
    caption: 'Validation',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'cardTypeId',
    caption: 'Card Type',
    fieldType: 'select',
    rules: '',
    type: 'select',
    value: '',
  },
  {
    key: 'cardSchemeId',
    caption: 'Card Scheme Id',
    fieldType: 'select',
    rules: '',
    type: 'select',
    value: '',
  },
  {
    key: 'cardIssuerId',
    caption: 'Card Issuer',
    fieldType: 'select',
    rules: '',
    type: 'select',
    value: '',
  },
  {
    key: 'description',
    caption: 'Description',
    fieldType: 'textarea',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'createdAt',
    caption: 'Created At',
    fieldType: 'date',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'archivedAt',
    caption: 'Archived At',
    fieldType: 'date',
    rules: '',
    type: 'text',
    value: '',
  },
]
