export default [
  {
    key: 'name',
    caption: 'Name',
    fieldType: 'text',
    rules: 'required|max:50',
    type: 'text',
    value: '',
  },
  {
    key: 'class',
    caption: 'Class',
    fieldType: 'text',
    rules: 'required',
    type: 'text',
    value: '',
  },
  {
    key: 'thumbnail',
    caption: 'Thumbnail',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'thumbnailGray',
    caption: 'Thumbnail Gray',
    fieldType: 'text',
    rules: '',
    type: '',
    value: '',
  },
  {
    key: 'chartColor',
    caption: 'Chart Color',
    fieldType: 'colorPicker',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'description',
    caption: 'Description',
    fieldType: 'textarea',
    rules: '',
    type: 'text',
    value: '',
  },
]
