export default [
  {
    key: 'name',
    caption: 'Name',
    rules: 'required|max:50',
    type: 'text',
    fieldType: 'text',
    value: '',
  },

  {
    key: 'minimumAmount',
    caption: 'Minimum Amount',
    rules: 'required|decimal',
    type: 'number',
    fieldType: 'text',
    value: '',
  },
  {
    key: 'maximumAmount',
    caption: 'Maximum Amount',
    rules: 'decimal',
    type: 'number',
    fieldType: 'text',
    value: '',
  },
  {
    key: 'processFee',
    caption: 'Process Fee',
    rules: 'required|decimal',
    type: 'number',
    fieldType: 'text',
    value: 0,
  },
  {
    key: 'shareAcquirer',
    caption: 'Share Acquirer (%)',
    rules: 'required',
    type: 'number',
    fieldType: 'text',
    value: 0,
  },
  {
    key: 'shareMerchant',
    caption: 'Share Merchant (%)',
    rules: 'required',
    type: 'number',
    fieldType: 'text',
    value: 0,
  },
  {
    key: 'shareMerchantWithPartner',
    caption: 'Share Merchant With Partner (%)',
    rules: 'required|decimal',
    type: 'number',
    fieldType: 'text',
    value: 0,
  },
  {
    key: 'sharePartner',
    caption: 'Share Partner (%)',
    rules: 'required|decimal',
    type: 'number',
    fieldType: 'text',
    value: 0,
  },
  {
    key: 'directSettlement',
    caption: 'Direct Settlement',
    rules: 'required|boolean',
    type: 'check',
    fieldType: 'check',
    value: false,
  },
  {
    key: 'gateway',
    caption: 'Gateway',
    rules: 'required|boolean',
    type: 'check',
    fieldType: 'check',
    value: false,
  },
  {
    key: 'hidden',
    caption: 'Hidden',
    rules: 'required|boolean',
    type: 'check',
    fieldType: 'check',
    value: false,
  },
  {
    key: 'merchantId',
    caption: 'Merchant',
    rules: 'required|integer',
    type: 'api',
    fieldType: 'api',
    value: '',
  },
  {
    key: 'acquirerConfigId',
    caption: 'Acquirer Config',
    rules: 'required|integer',
    type: 'select',
    fieldType: 'select',
    value: '',
  },
  {
    key: 'acquirerTypeId',
    caption: 'Acquirer Type',
    rules: 'required|integer',
    type: 'select',
    fieldType: 'select',
    value: '',
  },
  {
    key: 'description',
    caption: 'Description',
    rules: '',
    type: 'textarea',
    fieldType: 'textarea',
    value: '',
  },
  {
    key: 'acquirerCompanyId',
    caption: '',
    type: 'hidden',
    rules: '',
    fieldType: 'hidden',
    value: '',
  },
  {
    key: 'createdAt',
    caption: 'Created At',
    type: 'text',
    rules: '',
    fieldType: 'date',
    value: '',
  },
  {
    key: 'archivedAt',
    caption: 'Archived At',
    type: 'text',
    rules: '',
    fieldType: 'date',
    value: '',
  },
]
