export default [
  {
    key: 'idAlias',
    caption: 'Id Alias',
    fieldType: 'text',
    rules: 'required|max:27',
    type: 'text',
    value: '',
  },
  {
    key: 'name',
    caption: 'Name',
    fieldType: 'text',
    rules: 'required|max:50',
    type: 'text',
    value: '',
  },
  {
    key: 'email',
    caption: 'Email',
    fieldType: 'text',
    rules: 'required|email',
    type: 'text',
    value: '',
  },
  {
    key: 'website',
    caption: 'Website',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'locationLong',
    caption: 'Location Longitude',
    fieldType: 'text',
    rules: '',
    type: 'point',
    value: 0,
  },
  {
    key: 'locationLat',
    caption: 'Location Latitude',
    fieldType: 'text',
    rules: '',
    type: 'point',
    value: 0,
  },
  {
    key: 'streetAddress',
    caption: 'Street Address',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'district',
    caption: 'District',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'city',
    caption: 'City',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'province',
    caption: 'Province',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'postalCode',
    caption: 'Postal Code',
    fieldType: 'text',
    rules: 'number',
    type: 'text',
    value: '',
  },
  {
    key: 'phoneNumber',
    caption: 'Phone Number',
    fieldType: 'text',
    rules: 'max:30',
    type: 'text',
    value: '',
  },
  {
    key: 'ownershipType',
    caption: 'Ownership Type',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'rentDurationMonth',
    caption: 'Rent Duration Month',
    fieldType: 'text',
    rules: 'numeric|max:2',
    type: '',
    value: null,
  },
  {
    key: 'otherPaymentSystem',
    caption: 'Other Payment System',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  // {
  //   key: "outletPhotoResourceId",
  //   caption: "Outlet Photo Resource Id",
  //   fieldType: "text",
  //   rules: "",
  //   type: "file",
  //   value: ""
  // },
  {
    key: 'businessType',
    caption: 'Business Type',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'businessDurationMonth',
    caption: 'Business Duration Month',
    fieldType: 'text',
    rules: '',
    type: 'number',
    value: 0,
  },
  {
    key: 'businessMonthlyTurnover',
    caption: 'Business Monthly Turnover',
    fieldType: 'text',
    rules: 'numeric',
    type: 'number',
    value: 0,
  },
  {
    key: 'merchantName',
    caption: 'Merchant Name',
    fieldType: 'text',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'rentStartDate',
    caption: 'Rent Start Date',
    fieldType: 'datePicker',
    rules: '',
    type: 'date',
    value: null,
  },
  {
    key: 'description',
    caption: 'Description',
    fieldType: 'textarea',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'createdAt',
    caption: 'Date',
    fieldType: 'date',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'archivedAt',
    caption: 'Archived At',
    fieldType: 'date',
    rules: '',
    type: 'text',
    value: '',
  },
  {
    key: 'merchantId',
    caption: '',
    fieldType: 'hidden',
    rules: '',
    type: 'hidden',
    value: '',
  },
]

// merchantItems: [],
