# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "mikabackend" do |mikabackend|
    mikabackend.vm.box = "centos/7"
    mikabackend.vm.hostname = "mikabackend"

    mikabackend.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end

    mikabackend.vm.network "private_network", ip: "192.168.255.250"

    # mikabackend.vm.network "forwarded_port", guest: 80, host: 8080
    # mikabackend.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    # mikabackend.vm.network "public_network"
    # mikabackend.vm.synced_folder "../data", "/vagrant_data"

    mikabackend.vm.provision "shell", privileged: true, inline: "bash /vagrant/provision.sh"
  end
end
